"""add users table

Revision ID: 7457f460a674
Revises: 5d45c6201088
Create Date: 2021-09-07 05:08:39.851977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7457f460a674'
down_revision = '5d45c6201088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('level', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'level')
    # ### end Alembic commands ###
